# **A*** **Algorithem**
## **Task: Implement the A*** **Algorithm for the 8-Puzzle Problem**

## **Problem Statement**

You are given an initial state of an 8-puzzle, represented as a 3x3 grid. The objective is to move tiles by sliding them into the empty space (0) until the goal state is reached.

### **Example:**

#### **Initial State:**

[[0, 1, 3]

   [4, 2, 5]

   [7, 8, 6]]

#### **Goal State:**

[[1,2, 3]

   [4, 5, 6]

   [7, 8, 0]]


Your task is to write a Python program that finds the shortest path to solve the puzzle using the A algorithm* with the Manhattan distance heuristic.

### **Instructions:**

1. **Define the Manhattan Distance Heuristic Function**

    - The Manhattan distance for each tile is calculated as: 
    
        distance = |current row - goal row| + |current column - goal column|


    - Sum up the Manhattan distances of all misplaced tiles.

2. **Implement the** **A*** **Search Algorithm:**

    - Use a priority queue (min-heap) to store puzzle states based on their **f(n) = g(n) + h(n)** value.

    - **g(n)** = number of moves from the start state.

    - **h(n)** = Manhattan distance heuristic.

    - Generate new states by moving the empty tile (0) up, down, left, or right.

    - Avoid revisiting already explored states.

3. **Output the Solution Path**

    - If a solution is found, print the sequence of moves to reach the goal.

    - Display the number of steps taken.




### **Expected Output Format:**


#### **Initial State:**

    [[0, 1, 3]

    [4, 2, 5]

    [7, 8, 6]]



### **Solution Found in X Steps:**

    [(Move 1), (Move 2), ..., (Final Move)]


#### **Goal State:**

    [[1,2, 3]

    [4, 5, 6]

    [7, 8, 0]]

Ahmed ALI 22i-0825 E

In [ ]:
#Ahmed ALI 22i-0825 E
import heapq
from queue import PriorityQueue
import numpy as np

def get_coordinates(state, number):
    for i in range(len(state)):
        for j in range(len(state[0])):
            if(state[i][j] == number):
                return (i,j)

def manhattan_distance(state, goal_state):
    manhattan_sum = 0
    for i in range(len(state)):
        for j in range(len(state[0])):
            if(state[i][j] == 0):
                continue
            goal_coords = get_coordinates(goal_state, state[i][j])
            manhattan = abs(i - goal_coords[0]) + abs(j - goal_coords[1])
            manhattan_sum += manhattan
    return manhattan_sum

def get_neighbors(state):
    zero_coord = get_coordinates(state, 0)
    directions = [(0,1), (1,0), (0,-1), (-1,0)] 
    neighbor_states = []
    
    for dx, dy in directions:
        new_x, new_y = zero_coord[0] + dx, zero_coord[1] + dy
        if (0 <= new_x < len(state) and 0 <= new_y < len(state[0])):
            new_state = np.copy(state)
            new_state[zero_coord[0]][zero_coord[1]] = new_state[new_x][new_y]
            new_state[new_x][new_y] = 0
            neighbor_states.append(new_state)
    
    return neighbor_states

def goal_test(state, goal):
    return np.array_equal(state, goal)

def a_star_search(initial_state, goal_state):
    queue = PriorityQueue()
    visited = set() 
    g_scores = {str(initial_state): 0}  
    came_from = {}  
    
    # Convert initial state to tuple
    initial_tuple = str(initial_state)
    queue.put((0, 0, initial_state))  # (f_score, g_score, state)
    visited.add(initial_tuple)
    
    while not queue.empty():
        f_score, g_score, current_state = queue.get()
        
        if goal_test(current_state, goal_state):
            # Reconstruct path
            path = []
            current_tuple = str(current_state)
            while current_tuple in came_from:
                path.append(current_state)
                current_state = came_from[current_tuple]
                current_tuple = str(current_state)
            path.append(initial_state)
            return path[::-1], g_score  
        
        for neighbor in get_neighbors(current_state):
            neighbor_tuple = str(neighbor)
            new_g_score = g_score + 1
            
            if neighbor_tuple not in visited:
                visited.add(neighbor_tuple)
                g_scores[neighbor_tuple] = new_g_score
                h_score = manhattan_distance(neighbor, goal_state)
                f_score = new_g_score + h_score
                came_from[neighbor_tuple] = current_state
                queue.put((f_score, new_g_score, neighbor))
    
    return None, -1  # No solution found

def print_state(state):
    for i in range(len(state)):
        print(state[i])
    print()

def solve_8_puzzle(initial_state, goal_state):
    print("Initial state:")
    print_state(initial_state)
    print("Goal state:")
    print_state(goal_state)
    
    solution_path, moves = a_star_search(initial_state, goal_state)
    
    if solution_path:
        print(f"Solution found in {moves} moves:")
        for i, state in enumerate(solution_path):
            print(f"Step {i}:")
            print_state(state)
        print(f"Total moves: {moves}")
    else:
        print("No solution found")

# Example usage
initial_state = np.array([
    [0, 1, 3],
    [4, 2, 5],
    [7, 8, 6]
])

goal_state = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])

solve_8_puzzle(initial_state, goal_state)


Initial state:
[0 1 3]
[4 2 5]
[7 8 6]

Goal state:
[1 2 3]
[4 5 6]
[7 8 0]

Solution found in 4 moves:
Step 0:
[0 1 3]
[4 2 5]
[7 8 6]

Step 1:
[1 0 3]
[4 2 5]
[7 8 6]

Step 2:
[1 2 3]
[4 0 5]
[7 8 6]

Step 3:
[1 2 3]
[4 5 0]
[7 8 6]

Step 4:
[1 2 3]
[4 5 6]
[7 8 0]

Total moves: 4


# **Hill Climbing Algorithm**
## **Task: Implement the Hill Climbing Algorithm for the K-Rooks Problem**

### **Problem Statement**
You are given an 𝑁×𝑁 chessboard, and your task is to place K rooks on the board such that:
- No two rooks share the same column
- No rook is placed on diagonal (both main diagonals remain empty)

### **Example for N = 6:**


### **Initial Input State**
```
. R . . . .
. . . . . .
. R . . R .
. . . . . R
. . R . . .
. . . . . R
```

#### **Target K-Rocks**

```
. . . R . .
. . . . . .
R . . . R .
. R . . . .
. . . . . R
. . R . . . 
```


### **Instructions:**

1. **Define the Heuristic Function:**

    - The heuristic h is the total number of conflicts, calculated as:
        - Column Conflicts: More than one rook in a column.
        - Diagonal Conflicts: Any rook placed on the main diagonals.
    - A lower heuristic value is better.
    - A value of 0 means a valid K-Rooks placement.

2. **Implement the Hill Climbing Algorithm:**

    - Generate neighboring states by moving a rook within its row to another valid non-diagonal column.
    - Compute the heuristic for each neighbor.
    - Move to the best neighboring state if it reduces conflicts.
    - Stop when:
        - The heuristic reaches zero (valid solution found).
        - No better move is available (local optimum reached).

3. **Output the Solution**

    - Display the initial board and its heuristic value.
    - Display the final board configuration and the heuristic value.
    - Indicate whether a solution was found or if the algorithm got stuck.


In [ ]:
#Ahmed ALI 22i-0825 E

import random
import numpy as np

def calculate_conflicts(board, n, k):
    """
    TODO: Implement a function to calculate the number of conflicts in the current board.
    - This function should check:
      1. Column conflicts: More than one rook in a column.
      2. Diagonal conflicts: Rooks placed on the main or secondary diagonals.
    - The function should return the total number of conflicts.
    """
    conflicts = 0
    #for column conflicts
    for row in range(0,n):
        rooks = 0
        for col in range(0,n):
            if (board[col][row] == 'R'):
                rooks+=1
            if rooks >=2 :
                conflicts+=1
                break
    rooks = 0

    #For diagonal conflicts
    for row in range(0,n):
        if(board[row][row]=='R'):
            rooks+=1
    if rooks > 0:
        conflicts+=(rooks)
    rooks = 0
    for row in range(0,n):
        if(board[row][n-1-row]=='R'):
            rooks+=1
    if rooks > 0:
        conflicts+=(rooks)

    return conflicts

def get_rook_coords(board,n):
    coords = set()
    for i in range(0,n):
        for j in range(0,n):
            if(board[i][j]=='R'):
                coords.add((i,j))
    return coords

def is_valid_pos(i,j,n):
    if (i==j):
        return False
    if ((i+j)==n-1):
        return False
    
    return True

def get_neighbors(board, n, k,rooks):
    """
    TODO: Implement a function to generate neighboring boards.
    - Each neighbor should be created by moving a rook within its row to a new column.
    - Ensure that the new position is not on a diagonal.
    - Return a list of all possible neighboring boards.
    """
    neighbors = []
    # Iterate over all rooks positions
    for i,j in rooks:
        for pos in range(0,n):
            if pos == j: continue
            if (is_valid_pos(i,pos,n)):
                neighbour = np.copy(board)
                neighbour[i][j] = '.'
                neighbour[i][pos] = 'R'
                neighbors.append(neighbour)

    return neighbors

    

def hill_climbing_k_rooks(board, n, k):
    """
    TODO: Implement the Hill Climbing algorithm to solve the K-Rooks problem.
    - The algorithm should:
      1. Start with the given board.
      2. Generate neighbors and move to the best neighbor (with fewer conflicts).
      3. Stop when:
         - A solution with zero conflicts is found.
         - No better move is available (local optimum).
    - Return the final board and the number of conflicts.
    """
    h_score = calculate_conflicts(board,n,k)
    while h_score>0:
        neighbours = get_neighbors(board,n,k,get_rook_coords(board,n))
        found = False
        for neighbour in neighbours:
            h = calculate_conflicts(neighbour,n,k)
            if h < h_score:
                h_score = h
                board = np.copy(neighbour)
                found = True

        if not found:
            print("Local optimal found")
            return (board, h_score)
            
    return (board,h_score)
        




def solve_k_rooks(n, k, initial_board):
    """
    TODO: Use the above functions to solve the K-Rooks problem.
    - Print the initial board and its conflict count.
    - Run the Hill Climbing algorithm.
    - Print the final board and whether a solution was found.
    """
    print("Initial board:")
    print_board(initial_board)
    board, h_score = hill_climbing_k_rooks(initial_board,n,k)
    print("Final Board")
    print_board(board)
    if(h_score==0):
        print("Global Optimimum found")
    print("Conflicts: ", h_score)


def print_board(board):
    for row in board:
        print(" ".join(row))
    print()

n = 6  # Board size
k = 6  # Number of rooks to place

initial_board = [
    ['.', 'R', '.', '.', '.', '.'],  
    ['.', 'R', '.', '.', '.', '.'],  
    ['.', '.', '.', 'R', '.', '.'],
    ['.', '.', '.', '.', '.', 'R'],  
    ['.', '.', '.', 'R', '.', '.'],  
    ['.', '.', '.', '.', '.', 'R']   
]

solve_k_rooks(n, k, initial_board)


Initial board:
. R . . . .
. R . . . .
. . . R . .
. . . . . R
. . . R . .
. . . . . R

Final Board
. . . . R .
. . R . . .
R . . . . .
. . . . . R
. . . R . .
. R . . . .

Global Optimimum found
Conflicts:  0
